name: app
description: Houston Flutter App Framework
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  annotations:
    path: ../internal/annotations/
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  logger: ^2.0.1
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.10
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  mason: ^0.1.0-dev.50
  supabase_flutter: ^1.10.14
  go_router: ^10.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  build_runner:
  generators:
    path: ../internal/generators/
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

